### ISSUE TITLE
Relational Calls Prototype

### ISSUE THREAD

**Issue by thgie** [Participatory-Image-Archives/pia-search-and-curate#88]
Preview until 2022-06-29.

- [x] Show Collection for Simple (Sammel) Call
- [x] #95
- [x] Participatory-Image-Archives/pia-database#1
- [x] Participatory-Image-Archives/pia-search-and-curate#93
- [x] Participatory-Image-Archives/pia-search-and-curate#94
